# Generated by Django 5.1 on 2024-08-29 15:20

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=20)),
                ('subcategories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('prerequisites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('course_description', models.TextField(max_length=500)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_content', models.TextField()),
                ('prompt', models.TextField()),
                ('solution', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Course_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_solution', models.CharField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Course_app.question')),
            ],
        ),
    ]
