# Generated by Django 5.1 on 2024-09-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='users',
        ),
    ]
