# Generated by Django 5.1 on 2024-09-02 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_manager_app', '0001_initial'),
        ('Course_app', '0002_remove_course_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_plan',
            name='courses',
            field=models.ForeignKey(default=[], on_delete=django.db.models.deletion.CASCADE, to='Course_app.course'),
        ),
        migrations.AddField(
            model_name='lesson_plan',
            name='user_id',
            field=models.ForeignKey(default=[], on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
